### ISSUE TITLE
4K movies take too long to start

### ISSUE THREAD

**Issue by ggarra13** [darbyjohnston/tlRender#43]
Using play-glfw on a 4K mp4 movie takes tlRender about 4 seconds to start.  With tlplay creating the thumbnails it is much worse and playback is not smooth at least until the thumbnails are created.

In comparison, mrViewer opens the 4K movie in 1 second or less.

**Comment by darbyjohnston** [comment]
Hi, I think the slow down is from tlRender opening and closing the movie file multiple times. I've created a new git branch to implement a cache so that the opening and closing is minimized. If you have time could you test it out and see if there is an improvement on your test files? On my test files it seems about twice as fast. The branch is called "open" and "aad0b46cdef6a80bf65b57d1ea652c65279c35f6" is the latest commit. Thanks!

**Comment by darbyjohnston** [comment]
Thanks for testing out the "open" branch, I just merged it into main.
