### ISSUE TITLE
Add support for versioning (replacing) of clips

### ISSUE THREAD

**Issue by ggarra13** [darbyjohnston/tlRender#72]
A feature of mrViewer is that it allows changing versions of a clip (movie or sequence).  This would be an addition to the FilesModel to allow replacing a file with another one (and the likely recreation of the underlying timeline).  

The versioning (using a regex or other convention to match versions) can be done by the viewing application.

**Comment by darbyjohnston** [comment]
Currently the ```FilesModel``` class has ```add()```, ```close()```, ```closeAll()```, ```reload()```, and other functions for setting the "A" and "B" files. Are you suggesting also adding a ```replace()```? That sounds reasonable, you are welcome to create a PR.

**Comment by ggarra13** [comment]
I implemented a replace() method in mrv2's code, which works fine.   However, one thing that doesn't work as I'd like is that the new clip starts at the beginning, rather than keeping the original (replaced) clip currentTime.  I tried switching the currentTime with the TimelinePlayer->seek() function in the versioning update function, but it leads to blinking as the first frame is still shown.  Do you have any suggestions for that?

**Comment by ggarra13** [comment]
I managed to remove the frame popup by setting the new FileModelItem to init=true and filling all the struct variables.  However, there's still a black gap when switching from one version to the next.

**Comment by ggarra13** [comment]
Here's my implementation of FilesModel::replace() and the mrv2's callback in case you have an idea:

```
    void FilesModel::replace(const std::size_t index,
			     const std::shared_ptr<FilesModelItem>& item)
    {
        TLRENDER_P();

        p.files->setItem(index, item);

        p.a->setIfChanged(p.files->getItem(index));
        p.aIndex->setIfChanged(index);

        p.active->setIfChanged(_getActive());
        p.layers->setIfChanged(_getLayers());
    }
```

and here's the version update callback (hard-coded for now):

```
    void next_image_version_cb( Fl_Menu_* w, ViewerUI* ui )
    {
        auto player = ui->uiView->getTimelinePlayer();
        if ( !player ) return;

        const auto& time  = player->currentTime();
        const auto& model = ui->app->filesModel();
        const auto& settingsObject = ui->app->settingsObject();
        const auto& files = model->observeFiles();
        size_t numFiles = files->getSize();
        if ( numFiles == 0 ) return;
        
        auto Aindex = model->observeAIndex()->get();
        const auto& media = files->getItem( Aindex );
        std::cerr << "next image version for " << media->path.get()
                  << std::endl;
        std::string fileName =
            "/Users/gga/Pictures/bunny_v003/bunny_v003.0001.exr";
        
        
        auto item = std::make_shared<FilesModelItem>();
        item->init = true;
        item->path = file::Path(fileName);
        item->audioPath   = media->audioPath;
        item->inOutRange  = media->inOutRange;
        item->speed       = media->speed;
        item->audioOffset = media->audioOffset;
        item->videoLayer  = media->videoLayer;
        item->loop        = media->loop;
        item->currentTime = time;
        model->replace(Aindex, item);

    }
```

**Comment by darbyjohnston** [comment]
If you are seeing a black frame when switching I would take a look at your OpenGL widget and then work back from there.

**Comment by ggarra13** [comment]
I was seeing a black frame since when I call TimelineViewport->setTimelinePlayers() the players have a black frame with invalid time ( -1.0 / -1.0 ) when you call currentVideo() ( as if it is uninitialized ), but their currentTime() is properly set.  I worked around it by using time::isValid() but you might want to check it.

**Comment by darbyjohnston** [comment]
Thanks for pointing this out, I looked into it and found tlplay also had black frames when switching files and a couple of other issues causing flicker. I made a couple of changes to fix this:

* When an observer is created for ```TimelinePlayer::observeCurrentVideo()``` the callback function is executed immediately which I believe is causing the black frame you pointed out. Having the callback function executed immediately is usually the desired behavior but not in this case. To keep this from happening you can pass ```observer::CallbackAction::Suppress``` to the observer constructor: https://github.com/darbyjohnston/tlRender/blob/12041777dddceaf29b3c9df98f163b7b78b3dae0/lib/tlQt/TimelinePlayer.cpp#L92
* Since frames are loaded async there will be some period of time before the first frame is available. If the OpenGL viewport is updated before then you can also get a black screen. To prevent this from happening you should keep the frame from the old file around until the first frame of the new file is available.
* I also noticed some flickering when switching files in A/B comparison mode. This was caused by the "B" file loading the first frame and then loading the frame to match the current time of the "A" file. To prevent this I added an option to set the current frame when creating a new timeline: https://github.com/darbyjohnston/tlRender/blob/12041777dddceaf29b3c9df98f163b7b78b3dae0/lib/tlTimeline/TimelinePlayer.h#L96

If you have a chance check out the latest code and try switching files in tlplay, everything feels a lot smoother. Hopefully you can also incorporate similar changes in in mrv2.

**Comment by ggarra13** [comment]
I am closing this issue, as mrv2 already supports this.
